version: 2.1

orbs:
  python: circleci/python@1.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          command: |
            virtualenv .env -p python3
            source .env/bin/activate
            echo "flask" > requirements.txt ; echo "zappa" >> requirements.txt; echo "awscli" >> requirements.txt
            pip install -r requirements.txt
            aws configure --profile prod set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure --profile prod set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure --profile prod set region $AWS_DEFAULT_REGION
            aws configure --profile prod list
            zappa update prod
          name: All tasks for deploying using zappa

workflows:
  main:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                -main

