version: 2.1

orbs:
  python: circleci/python@1.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      #- python/load-cache
      #- python/install-deps
      #- python/save-cache
      - run:
          name: Set AWS Credentials
          command: |
            echo aws configure --profile default set aws_access_key_id $AWS_ACCESS_KEY_ID
            echo aws configure --profile default set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            echo aws configure --profile default set region $AWS_DEFAULT_REGION
            echo aws configure --profile default list
      - run:
          #command: ./manage.py test
          #name: Test
          command: echo "flask" > requirements.txt ; echo "zappa" >> requirements.txt
          name: Create requirements file
      - run: 
          command: pip install -r requirements.txt
          name: Installing requirements
      - run: 
          command: zappa deploy prod
          name: Deploying to prod using zappa

workflows:
  main:
    jobs:
      - build-and-test
